# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_clan.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addClan(object):
    def setupUi(self, addClan):
        addClan.setObjectName("addClan")
        addClan.resize(1070, 720)
        self.centralwidget = QtWidgets.QWidget(addClan)
        self.centralwidget.setObjectName("centralwidget")
        self.background_image = QtWidgets.QLabel(self.centralwidget)
        self.background_image.setGeometry(QtCore.QRect(-10, 0, 1081, 741))
        self.background_image.setStyleSheet("border-image: url(:/addClan/background image.png);")
        self.background_image.setText("")
        self.background_image.setScaledContents(True)
        self.background_image.setObjectName("background_image")
        self.clans_list = QtWidgets.QGroupBox(self.centralwidget)
        self.clans_list.setGeometry(QtCore.QRect(110, 100, 861, 401))
        self.clans_list.setAutoFillBackground(False)
        self.clans_list.setStyleSheet("QGroupBox#clans_list{\n"
"border: 2px solid gray;\n"
"border-color: #424242;\n"
"background-color: white;\n"
"}")
        self.clans_list.setTitle("")
        self.clans_list.setObjectName("clans_list")
        self.saved_clan_0 = QtWidgets.QGroupBox(self.clans_list)
        self.saved_clan_0.setGeometry(QtCore.QRect(1, 0, 859, 80))
        self.saved_clan_0.setStyleSheet("QGroupBox{\n"
"border: 1px solid gray;\n"
"border-color: #424242;\n"
"background-color: white;\n"
"}\n"
"\n"
"QGroupBox:hover{\n"
"    background-color: red;\n"
"}")
        self.saved_clan_0.setTitle("")
        self.saved_clan_0.setObjectName("saved_clan_0")
        self.clan_shield_0 = QtWidgets.QLabel(self.saved_clan_0)
        self.clan_shield_0.setGeometry(QtCore.QRect(5, 6, 68, 68))
        self.clan_shield_0.setMouseTracking(False)
        self.clan_shield_0.setStyleSheet("")
        self.clan_shield_0.setText("")
        self.clan_shield_0.setScaledContents(True)
        self.clan_shield_0.setObjectName("clan_shield_0")
        self.clan_name_0 = QtWidgets.QLabel(self.saved_clan_0)
        self.clan_name_0.setGeometry(QtCore.QRect(90, 18, 561, 51))
        font = QtGui.QFont()
        font.setFamily("Supercell-Magic")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.clan_name_0.setFont(font)
        self.clan_name_0.setStyleSheet("")
        self.clan_name_0.setText("")
        self.clan_name_0.setObjectName("clan_name_0")
        self.frame_0 = QtWidgets.QFrame(self.saved_clan_0)
        self.frame_0.setGeometry(QtCore.QRect(1, 1, 857, 78))
        self.frame_0.setMouseTracking(True)
        self.frame_0.setStyleSheet("QFrame {\n"
"background-color: white;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"background-color: rgb(227, 227, 227);\n"
"}")
        self.frame_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_0.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_0.setObjectName("frame_0")
        self.delete_0 = QtWidgets.QPushButton(self.saved_clan_0)
        self.delete_0.setGeometry(QtCore.QRect(788, 10, 65, 61))
        self.delete_0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_0.setStyleSheet("border-image: url(:/addClan/delete.png);")
        self.delete_0.setText("")
        self.delete_0.setObjectName("delete_0")
        self.confirm_0 = QtWidgets.QPushButton(self.saved_clan_0)
        self.confirm_0.setGeometry(QtCore.QRect(720, 10, 65, 65))
        self.confirm_0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confirm_0.setStyleSheet("border-image: url(:/addClan/confirmtick.png);")
        self.confirm_0.setText("")
        self.confirm_0.setObjectName("confirm_0")
        self.frame_0.raise_()
        self.clan_name_0.raise_()
        self.clan_shield_0.raise_()
        self.delete_0.raise_()
        self.confirm_0.raise_()
        self.saved_clan_1 = QtWidgets.QGroupBox(self.clans_list)
        self.saved_clan_1.setGeometry(QtCore.QRect(1, 80, 859, 80))
        self.saved_clan_1.setStyleSheet("QGroupBox{\n"
"border: 1px solid gray;\n"
"border-color: #424242;\n"
"background-color: white;\n"
"}")
        self.saved_clan_1.setTitle("")
        self.saved_clan_1.setObjectName("saved_clan_1")
        self.clan_shield_1 = QtWidgets.QLabel(self.saved_clan_1)
        self.clan_shield_1.setGeometry(QtCore.QRect(5, 6, 68, 68))
        self.clan_shield_1.setStyleSheet("")
        self.clan_shield_1.setText("")
        self.clan_shield_1.setScaledContents(True)
        self.clan_shield_1.setObjectName("clan_shield_1")
        self.clan_name_1 = QtWidgets.QLabel(self.saved_clan_1)
        self.clan_name_1.setGeometry(QtCore.QRect(90, 18, 561, 51))
        font = QtGui.QFont()
        font.setFamily("Supercell-Magic")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.clan_name_1.setFont(font)
        self.clan_name_1.setText("")
        self.clan_name_1.setObjectName("clan_name_1")
        self.frame_1 = QtWidgets.QFrame(self.saved_clan_1)
        self.frame_1.setGeometry(QtCore.QRect(1, 1, 857, 78))
        self.frame_1.setStyleSheet("QFrame {\n"
"background-color: white;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"background-color: rgb(227, 227, 227);\n"
"}")
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.delete_1 = QtWidgets.QPushButton(self.saved_clan_1)
        self.delete_1.setGeometry(QtCore.QRect(788, 10, 65, 61))
        self.delete_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_1.setStyleSheet("border-image: url(:/addClan/delete.png);")
        self.delete_1.setText("")
        self.delete_1.setObjectName("delete_1")
        self.confirm_1 = QtWidgets.QPushButton(self.saved_clan_1)
        self.confirm_1.setGeometry(QtCore.QRect(720, 10, 65, 65))
        self.confirm_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confirm_1.setStyleSheet("border-image: url(:/addClan/confirmtick.png);")
        self.confirm_1.setText("")
        self.confirm_1.setObjectName("confirm_1")
        self.frame_1.raise_()
        self.clan_name_1.raise_()
        self.clan_shield_1.raise_()
        self.delete_1.raise_()
        self.confirm_1.raise_()
        self.saved_clan_2 = QtWidgets.QGroupBox(self.clans_list)
        self.saved_clan_2.setGeometry(QtCore.QRect(1, 160, 859, 80))
        self.saved_clan_2.setStyleSheet("QGroupBox{\n"
"border: 1px solid gray;\n"
"border-color: #424242;\n"
"background-color: white;\n"
"}")
        self.saved_clan_2.setTitle("")
        self.saved_clan_2.setObjectName("saved_clan_2")
        self.clan_shield_2 = QtWidgets.QLabel(self.saved_clan_2)
        self.clan_shield_2.setGeometry(QtCore.QRect(5, 6, 68, 68))
        self.clan_shield_2.setStyleSheet("")
        self.clan_shield_2.setText("")
        self.clan_shield_2.setScaledContents(True)
        self.clan_shield_2.setObjectName("clan_shield_2")
        self.clan_name_2 = QtWidgets.QLabel(self.saved_clan_2)
        self.clan_name_2.setGeometry(QtCore.QRect(90, 18, 561, 51))
        font = QtGui.QFont()
        font.setFamily("Supercell-Magic")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.clan_name_2.setFont(font)
        self.clan_name_2.setText("")
        self.clan_name_2.setObjectName("clan_name_2")
        self.frame_2 = QtWidgets.QFrame(self.saved_clan_2)
        self.frame_2.setGeometry(QtCore.QRect(1, 1, 857, 78))
        self.frame_2.setStyleSheet("QFrame {\n"
"background-color: white;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"background-color: rgb(227, 227, 227);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.delete_2 = QtWidgets.QPushButton(self.saved_clan_2)
        self.delete_2.setGeometry(QtCore.QRect(788, 10, 65, 61))
        self.delete_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_2.setStyleSheet("border-image: url(:/addClan/delete.png);")
        self.delete_2.setText("")
        self.delete_2.setObjectName("delete_2")
        self.confirm_2 = QtWidgets.QPushButton(self.saved_clan_2)
        self.confirm_2.setGeometry(QtCore.QRect(720, 10, 65, 65))
        self.confirm_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confirm_2.setStyleSheet("border-image: url(:/addClan/confirmtick.png);")
        self.confirm_2.setText("")
        self.confirm_2.setObjectName("confirm_2")
        self.frame_2.raise_()
        self.clan_name_2.raise_()
        self.clan_shield_2.raise_()
        self.delete_2.raise_()
        self.confirm_2.raise_()
        self.saved_clan_3 = QtWidgets.QGroupBox(self.clans_list)
        self.saved_clan_3.setGeometry(QtCore.QRect(1, 240, 859, 80))
        self.saved_clan_3.setStyleSheet("QGroupBox{\n"
"border: 1px solid gray;\n"
"border-color: #424242;\n"
"background-color: white;\n"
"}")
        self.saved_clan_3.setTitle("")
        self.saved_clan_3.setObjectName("saved_clan_3")
        self.clan_shield_3 = QtWidgets.QLabel(self.saved_clan_3)
        self.clan_shield_3.setGeometry(QtCore.QRect(5, 6, 68, 68))
        self.clan_shield_3.setStyleSheet("")
        self.clan_shield_3.setText("")
        self.clan_shield_3.setScaledContents(True)
        self.clan_shield_3.setObjectName("clan_shield_3")
        self.clan_name_3 = QtWidgets.QLabel(self.saved_clan_3)
        self.clan_name_3.setGeometry(QtCore.QRect(90, 18, 561, 51))
        font = QtGui.QFont()
        font.setFamily("Supercell-Magic")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.clan_name_3.setFont(font)
        self.clan_name_3.setText("")
        self.clan_name_3.setObjectName("clan_name_3")
        self.frame_3 = QtWidgets.QFrame(self.saved_clan_3)
        self.frame_3.setGeometry(QtCore.QRect(1, 1, 857, 78))
        self.frame_3.setStyleSheet("QFrame {\n"
"background-color: white;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"background-color: rgb(227, 227, 227);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.delete_3 = QtWidgets.QPushButton(self.saved_clan_3)
        self.delete_3.setGeometry(QtCore.QRect(788, 10, 65, 61))
        self.delete_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_3.setStyleSheet("border-image: url(:/addClan/delete.png);")
        self.delete_3.setText("")
        self.delete_3.setObjectName("delete_3")
        self.confirm_3 = QtWidgets.QPushButton(self.saved_clan_3)
        self.confirm_3.setGeometry(QtCore.QRect(720, 10, 65, 65))
        self.confirm_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confirm_3.setStyleSheet("border-image: url(:/addClan/confirmtick.png);")
        self.confirm_3.setText("")
        self.confirm_3.setObjectName("confirm_3")
        self.frame_3.raise_()
        self.clan_name_3.raise_()
        self.clan_shield_3.raise_()
        self.delete_3.raise_()
        self.confirm_3.raise_()
        self.saved_clan_4 = QtWidgets.QGroupBox(self.clans_list)
        self.saved_clan_4.setGeometry(QtCore.QRect(1, 320, 859, 80))
        self.saved_clan_4.setStyleSheet("QGroupBox{\n"
"border: 1px solid gray;\n"
"border-color: #424242;\n"
"background-color: white;\n"
"}")
        self.saved_clan_4.setTitle("")
        self.saved_clan_4.setObjectName("saved_clan_4")
        self.clan_shield_4 = QtWidgets.QLabel(self.saved_clan_4)
        self.clan_shield_4.setGeometry(QtCore.QRect(5, 6, 68, 68))
        self.clan_shield_4.setStyleSheet("")
        self.clan_shield_4.setText("")
        self.clan_shield_4.setScaledContents(True)
        self.clan_shield_4.setObjectName("clan_shield_4")
        self.clan_name_4 = QtWidgets.QLabel(self.saved_clan_4)
        self.clan_name_4.setGeometry(QtCore.QRect(90, 18, 561, 51))
        font = QtGui.QFont()
        font.setFamily("Supercell-Magic")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.clan_name_4.setFont(font)
        self.clan_name_4.setText("")
        self.clan_name_4.setObjectName("clan_name_4")
        self.frame_4 = QtWidgets.QFrame(self.saved_clan_4)
        self.frame_4.setGeometry(QtCore.QRect(1, 1, 857, 78))
        self.frame_4.setStyleSheet("QFrame {\n"
"background-color: white;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"background-color: rgb(227, 227, 227);\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.delete_4 = QtWidgets.QPushButton(self.saved_clan_4)
        self.delete_4.setGeometry(QtCore.QRect(788, 10, 65, 61))
        self.delete_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_4.setStyleSheet("border-image: url(:/addClan/delete.png);")
        self.delete_4.setText("")
        self.delete_4.setObjectName("delete_4")
        self.confirm_4 = QtWidgets.QPushButton(self.saved_clan_4)
        self.confirm_4.setGeometry(QtCore.QRect(720, 10, 65, 65))
        self.confirm_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confirm_4.setStyleSheet("border-image: url(:/addClan/confirmtick.png);")
        self.confirm_4.setText("")
        self.confirm_4.setObjectName("confirm_4")
        self.frame_4.raise_()
        self.clan_name_4.raise_()
        self.clan_shield_4.raise_()
        self.delete_4.raise_()
        self.confirm_4.raise_()
        self.add_clan_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_clan_button.setGeometry(QtCore.QRect(109, 520, 861, 81))
        font = QtGui.QFont()
        font.setFamily("Supercell-Magic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.add_clan_button.setFont(font)
        self.add_clan_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_clan_button.setAutoFillBackground(False)
        self.add_clan_button.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.0511364, y1:0.5, x2:0.938, y2:0.534091, stop:0 rgba(231, 163, 4, 255), stop:1 rgba(238, 211, 4, 255));\n"
"    color: white;\n"
"     border-radius: 10; \n"
"    padding: 6; \n"
"    border-style: outset;\n"
"    border-width: 1;\n"
"    border-top-color: rgb(135, 135, 135);\n"
"    border-left-color: rgb(135, 135, 135);\n"
"    border-right-color: rgb(0, 0, 0);\n"
"    border-bottom-color: rgb(0, 0, 0);\n"
"    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: outset;\n"
"    border-top-color: rgb(0, 0, 0);\n"
"    border-left-color: rgb(0, 0, 0);\n"
"    border-right-color: rgb(135, 135, 135);\n"
"    border-bottom-color: rgb(135, 135, 135);\n"
"    \n"
"}")
        self.add_clan_button.setCheckable(False)
        self.add_clan_button.setChecked(False)
        self.add_clan_button.setDefault(False)
        self.add_clan_button.setFlat(False)
        self.add_clan_button.setObjectName("add_clan_button")
        self.add_clan_group = QtWidgets.QGroupBox(self.centralwidget)
        self.add_clan_group.setGeometry(QtCore.QRect(220, 150, 631, 301))
        self.add_clan_group.setAutoFillBackground(False)
        self.add_clan_group.setStyleSheet("QGroupBox {\n"
"border: 2px solid gray;\n"
"border-color: #424242;\n"
"border-radius: 15px;\n"
"background-color: white\n"
"}")
        self.add_clan_group.setTitle("")
        self.add_clan_group.setObjectName("add_clan_group")
        self.clan_tag_label = QtWidgets.QLabel(self.add_clan_group)
        self.clan_tag_label.setGeometry(QtCore.QRect(20, 10, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Supercell-Magic")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.clan_tag_label.setFont(font)
        self.clan_tag_label.setObjectName("clan_tag_label")
        self.clan_entry = QtWidgets.QLineEdit(self.add_clan_group)
        self.clan_entry.setGeometry(QtCore.QRect(20, 60, 461, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.clan_entry.setFont(font)
        self.clan_entry.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(222, 222, 222);\n"
"    border-radius: 7;\n"
"    border: 1px solid black\n"
"}")
        self.clan_entry.setObjectName("clan_entry")
        self.search_clan_button = QtWidgets.QPushButton(self.add_clan_group)
        self.search_clan_button.setGeometry(QtCore.QRect(490, 60, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Supercell-Magic")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.search_clan_button.setFont(font)
        self.search_clan_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search_clan_button.setAutoFillBackground(False)
        self.search_clan_button.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0.0511364, y1:0.5, x2:0.938, y2:0.534091, stop:0 rgba(231, 163, 4, 255), stop:1 rgba(238, 211, 4, 255));\n"
"    color: white;\n"
"     border-radius: 10; \n"
"    padding: 6; \n"
"    border-style: outset;\n"
"    border-width: 1;\n"
"    border-top-color: rgb(135, 135, 135);\n"
"    border-left-color: rgb(135, 135, 135);\n"
"    border-right-color: rgb(0, 0, 0);\n"
"    border-bottom-color: rgb(0, 0, 0);\n"
"    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: outset;\n"
"    border-top-color: rgb(0, 0, 0);\n"
"    border-left-color: rgb(0, 0, 0);\n"
"    border-right-color: rgb(135, 135, 135);\n"
"    border-bottom-color: rgb(135, 135, 135);\n"
"    \n"
"}")
        self.search_clan_button.setCheckable(False)
        self.search_clan_button.setChecked(False)
        self.search_clan_button.setDefault(False)
        self.search_clan_button.setFlat(False)
        self.search_clan_button.setObjectName("search_clan_button")
        self.clan_shield = QtWidgets.QLabel(self.add_clan_group)
        self.clan_shield.setGeometry(QtCore.QRect(10, 110, 120, 120))
        self.clan_shield.setStyleSheet("")
        self.clan_shield.setText("")
        self.clan_shield.setScaledContents(True)
        self.clan_shield.setObjectName("clan_shield")
        self.clan_name = QtWidgets.QLabel(self.add_clan_group)
        self.clan_name.setGeometry(QtCore.QRect(140, 110, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Supercell-Magic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.clan_name.setFont(font)
        self.clan_name.setText("")
        self.clan_name.setObjectName("clan_name")
        self.clan_description = QtWidgets.QTextEdit(self.add_clan_group)
        self.clan_description.setGeometry(QtCore.QRect(140, 155, 471, 65))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.clan_description.setFont(font)
        self.clan_description.setStyleSheet("QTextEdit {\n"
"    background-color: rgb(222, 222, 222);\n"
"    border-radius: 7;\n"
"    border: 1px solid black\n"
"}")
        self.clan_description.setReadOnly(True)
        self.clan_description.setObjectName("clan_description")
        self.no_clan = QtWidgets.QLabel(self.add_clan_group)
        self.no_clan.setGeometry(QtCore.QRect(20, 100, 371, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.no_clan.setFont(font)
        self.no_clan.setStyleSheet("color: red")
        self.no_clan.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.no_clan.setObjectName("no_clan")
        self.confirm_clan = QtWidgets.QPushButton(self.add_clan_group)
        self.confirm_clan.setGeometry(QtCore.QRect(20, 230, 591, 61))
        font = QtGui.QFont()
        font.setFamily("Supercell-Magic")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.confirm_clan.setFont(font)
        self.confirm_clan.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confirm_clan.setAutoFillBackground(False)
        self.confirm_clan.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0.125, y1:0.466, x2:0.938, y2:0.472, stop:0 rgba(0, 144, 24, 255), stop:1 rgba(124, 255, 38, 255));\n"
"    color: white;\n"
"     border-radius: 10; \n"
"    padding: 6; \n"
"    border-style: outset;\n"
"    border-width: 1;\n"
"    border-top-color: rgb(135, 135, 135);\n"
"    border-left-color: rgb(135, 135, 135);\n"
"    border-right-color: rgb(0, 0, 0);\n"
"    border-bottom-color: rgb(0, 0, 0);\n"
"    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: outset;\n"
"    border-top-color: rgb(0, 0, 0);\n"
"    border-left-color: rgb(0, 0, 0);\n"
"    border-right-color: rgb(135, 135, 135);\n"
"    border-bottom-color: rgb(135, 135, 135);\n"
"    \n"
"}")
        self.confirm_clan.setCheckable(False)
        self.confirm_clan.setChecked(False)
        self.confirm_clan.setDefault(False)
        self.confirm_clan.setFlat(False)
        self.confirm_clan.setObjectName("confirm_clan")
        self.add_clan_close_button = QtWidgets.QPushButton(self.add_clan_group)
        self.add_clan_close_button.setGeometry(QtCore.QRect(580, 10, 37, 37))
        self.add_clan_close_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_clan_close_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.add_clan_close_button.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    border-radius: 6;\n"
"    image: url(:/titleScreen/closebutton.png);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"}")
        self.add_clan_close_button.setText("")
        self.add_clan_close_button.setIconSize(QtCore.QSize(40, 40))
        self.add_clan_close_button.setObjectName("add_clan_close_button")
        self.logout_button = QtWidgets.QPushButton(self.centralwidget)
        self.logout_button.setGeometry(QtCore.QRect(830, 10, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Supercell-Magic")
        font.setBold(True)
        font.setWeight(75)
        self.logout_button.setFont(font)
        self.logout_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logout_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 62, 3);\n"
"    color: white;\n"
"    border-color: rgb(255, 255, 255);\n"
"    border-radius: 6;\n"
"    border-style: outset;\n"
"    border-width: 1;\n"
"    border-top-color: rgb(135, 135, 135);\n"
"    border-left-color: rgb(135, 135, 135);\n"
"    border-right-color: rgb(0, 0, 0);\n"
"    border-bottom-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: outset;\n"
"    border-top-color: rgb(0, 0, 0);\n"
"    border-left-color: rgb(0, 0, 0);\n"
"    border-right-color: rgb(135, 135, 135);\n"
"    border-bottom-color: rgb(135, 135, 135);\n"
"    \n"
"}\n"
"")
        self.logout_button.setObjectName("logout_button")
        self.background_image.raise_()
        self.clans_list.raise_()
        self.add_clan_button.raise_()
        self.logout_button.raise_()
        self.add_clan_group.raise_()
        addClan.setCentralWidget(self.centralwidget)

        self.retranslateUi(addClan)
        QtCore.QMetaObject.connectSlotsByName(addClan)

    def retranslateUi(self, addClan):
        _translate = QtCore.QCoreApplication.translate
        addClan.setWindowTitle(_translate("addClan", "MainWindow"))
        self.add_clan_button.setText(_translate("addClan", "ADD NEW CLAN"))
        self.clan_tag_label.setText(_translate("addClan", "Clan Tag"))
        self.clan_entry.setText(_translate("addClan", "#"))
        self.clan_entry.setPlaceholderText(_translate("addClan", "#"))
        self.search_clan_button.setText(_translate("addClan", "SEARCH"))
        self.no_clan.setText(_translate("addClan", "No clan found! Please try again."))
        self.confirm_clan.setText(_translate("addClan", "CONFIRM SELECTION"))
        self.logout_button.setText(_translate("addClan", "LOG OUT: sam"))
import source


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addClan = QtWidgets.QMainWindow()
    ui = Ui_addClan()
    ui.setupUi(addClan)
    addClan.show()
    sys.exit(app.exec_())
