# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selection_function.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_selectionFunction(object):
    def setupUi(self, selectionFunction):
        selectionFunction.setObjectName("selectionFunction")
        selectionFunction.resize(1070, 720)
        self.centralwidget = QtWidgets.QWidget(selectionFunction)
        self.centralwidget.setObjectName("centralwidget")
        self.background_image = QtWidgets.QLabel(self.centralwidget)
        self.background_image.setGeometry(QtCore.QRect(-10, 0, 1081, 741))
        self.background_image.setStyleSheet("border-image: url(:/titleScreen/background image.png);")
        self.background_image.setText("")
        self.background_image.setObjectName("background_image")
        self.logout_button = QtWidgets.QPushButton(self.centralwidget)
        self.logout_button.setGeometry(QtCore.QRect(830, 10, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Supercell-Magic")
        font.setBold(True)
        font.setWeight(75)
        self.logout_button.setFont(font)
        self.logout_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logout_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 62, 3);\n"
"    color: white;\n"
"    border-color: rgb(255, 255, 255);\n"
"    border-radius: 6;\n"
"    border-style: outset;\n"
"    border-width: 1;\n"
"    border-top-color: rgb(135, 135, 135);\n"
"    border-left-color: rgb(135, 135, 135);\n"
"    border-right-color: rgb(0, 0, 0);\n"
"    border-bottom-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: outset;\n"
"    border-top-color: rgb(0, 0, 0);\n"
"    border-left-color: rgb(0, 0, 0);\n"
"    border-right-color: rgb(135, 135, 135);\n"
"    border-bottom-color: rgb(135, 135, 135);\n"
"    \n"
"}\n"
"")
        self.logout_button.setObjectName("logout_button")
        self.change_clan_button = QtWidgets.QPushButton(self.centralwidget)
        self.change_clan_button.setGeometry(QtCore.QRect(590, 10, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Supercell-Magic")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.change_clan_button.setFont(font)
        self.change_clan_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.change_clan_button.setAutoFillBackground(False)
        self.change_clan_button.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.0511364, y1:0.5, x2:0.938, y2:0.534091, stop:0 rgba(231, 163, 4, 255), stop:1 rgba(238, 211, 4, 255));\n"
"    color: white;\n"
"     border-radius: 6; \n"
"    padding: 6; \n"
"    border-style: outset;\n"
"    border-width: 1;\n"
"    border-top-color: rgb(135, 135, 135);\n"
"    border-left-color: rgb(135, 135, 135);\n"
"    border-right-color: rgb(0, 0, 0);\n"
"    border-bottom-color: rgb(0, 0, 0);\n"
"    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: outset;\n"
"    border-top-color: rgb(0, 0, 0);\n"
"    border-left-color: rgb(0, 0, 0);\n"
"    border-right-color: rgb(135, 135, 135);\n"
"    border-bottom-color: rgb(135, 135, 135);\n"
"    \n"
"}")
        self.change_clan_button.setCheckable(False)
        self.change_clan_button.setChecked(False)
        self.change_clan_button.setDefault(False)
        self.change_clan_button.setFlat(False)
        self.change_clan_button.setObjectName("change_clan_button")
        self.clan_shield = QtWidgets.QLabel(self.centralwidget)
        self.clan_shield.setGeometry(QtCore.QRect(0, 10, 141, 141))
        self.clan_shield.setStyleSheet("")
        self.clan_shield.setText("")
        self.clan_shield.setScaledContents(True)
        self.clan_shield.setObjectName("clan_shield")
        self.clan_name = QtWidgets.QLabel(self.centralwidget)
        self.clan_name.setGeometry(QtCore.QRect(140, 60, 601, 61))
        font = QtGui.QFont()
        font.setFamily("Supercell-Magic")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.clan_name.setFont(font)
        self.clan_name.setStyleSheet("color: white;")
        self.clan_name.setText("")
        self.clan_name.setObjectName("clan_name")
        self.members_button = QtWidgets.QPushButton(self.centralwidget)
        self.members_button.setGeometry(QtCore.QRect(20, 230, 501, 71))
        font = QtGui.QFont()
        font.setFamily("Supercell-Magic")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.members_button.setFont(font)
        self.members_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.members_button.setAutoFillBackground(False)
        self.members_button.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.0511364, y1:0.5, x2:0.938, y2:0.534091, stop:0 rgba(231, 163, 4, 255), stop:1 rgba(238, 211, 4, 255));\n"
"    color: white;\n"
"     border-radius: 6; \n"
"    padding: 6; \n"
"    border-style: outset;\n"
"    border-width: 1;\n"
"    border-top-color: rgb(135, 135, 135);\n"
"    border-left-color: rgb(135, 135, 135);\n"
"    border-right-color: rgb(0, 0, 0);\n"
"    border-bottom-color: rgb(0, 0, 0);\n"
"    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: outset;\n"
"    border-top-color: rgb(0, 0, 0);\n"
"    border-left-color: rgb(0, 0, 0);\n"
"    border-right-color: rgb(135, 135, 135);\n"
"    border-bottom-color: rgb(135, 135, 135);\n"
"    \n"
"}")
        self.members_button.setCheckable(False)
        self.members_button.setChecked(False)
        self.members_button.setDefault(False)
        self.members_button.setFlat(False)
        self.members_button.setObjectName("members_button")
        self.war_button = QtWidgets.QPushButton(self.centralwidget)
        self.war_button.setGeometry(QtCore.QRect(20, 340, 501, 71))
        font = QtGui.QFont()
        font.setFamily("Supercell-Magic")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.war_button.setFont(font)
        self.war_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.war_button.setAutoFillBackground(False)
        self.war_button.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.0511364, y1:0.5, x2:0.938, y2:0.534091, stop:0 rgba(231, 163, 4, 255), stop:1 rgba(238, 211, 4, 255));\n"
"    color: white;\n"
"     border-radius: 6; \n"
"    padding: 6; \n"
"    border-style: outset;\n"
"    border-width: 1;\n"
"    border-top-color: rgb(135, 135, 135);\n"
"    border-left-color: rgb(135, 135, 135);\n"
"    border-right-color: rgb(0, 0, 0);\n"
"    border-bottom-color: rgb(0, 0, 0);\n"
"    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: outset;\n"
"    border-top-color: rgb(0, 0, 0);\n"
"    border-left-color: rgb(0, 0, 0);\n"
"    border-right-color: rgb(135, 135, 135);\n"
"    border-bottom-color: rgb(135, 135, 135);\n"
"    \n"
"}")
        self.war_button.setCheckable(False)
        self.war_button.setChecked(False)
        self.war_button.setDefault(False)
        self.war_button.setFlat(False)
        self.war_button.setObjectName("war_button")
        self.event_button = QtWidgets.QPushButton(self.centralwidget)
        self.event_button.setGeometry(QtCore.QRect(20, 450, 501, 71))
        font = QtGui.QFont()
        font.setFamily("Supercell-Magic")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.event_button.setFont(font)
        self.event_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.event_button.setAutoFillBackground(False)
        self.event_button.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.0511364, y1:0.5, x2:0.938, y2:0.534091, stop:0 rgba(231, 163, 4, 255), stop:1 rgba(238, 211, 4, 255));\n"
"    color: white;\n"
"     border-radius: 6; \n"
"    padding: 6; \n"
"    border-style: outset;\n"
"    border-width: 1;\n"
"    border-top-color: rgb(135, 135, 135);\n"
"    border-left-color: rgb(135, 135, 135);\n"
"    border-right-color: rgb(0, 0, 0);\n"
"    border-bottom-color: rgb(0, 0, 0);\n"
"    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: outset;\n"
"    border-top-color: rgb(0, 0, 0);\n"
"    border-left-color: rgb(0, 0, 0);\n"
"    border-right-color: rgb(135, 135, 135);\n"
"    border-bottom-color: rgb(135, 135, 135);\n"
"    \n"
"}")
        self.event_button.setCheckable(False)
        self.event_button.setChecked(False)
        self.event_button.setDefault(False)
        self.event_button.setFlat(False)
        self.event_button.setObjectName("event_button")
        self.function_description = QtWidgets.QTextEdit(self.centralwidget)
        self.function_description.setGeometry(QtCore.QRect(590, 70, 471, 611))
        self.function_description.setMouseTracking(False)
        self.function_description.setStyleSheet("QTextEdit {\n"
"    border: 2px solid gray;\n"
"    border-color: #424242;\n"
"    border-radius: 15px;\n"
"    background-color: white\n"
"}")
        self.function_description.setReadOnly(True)
        self.function_description.setObjectName("function_description")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(0, 701, 1071, 20))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk:horizontal {\n"
"    background-color: rgb(255, 202, 8);\n"
"}")
        self.progressBar.setProperty("value", 98)
        self.progressBar.setObjectName("progressBar")
        self.filler_label = QtWidgets.QLabel(self.centralwidget)
        self.filler_label.setGeometry(QtCore.QRect(0, 0, 1071, 721))
        self.filler_label.setStyleSheet("")
        self.filler_label.setText("")
        self.filler_label.setObjectName("filler_label")
        selectionFunction.setCentralWidget(self.centralwidget)

        self.retranslateUi(selectionFunction)
        QtCore.QMetaObject.connectSlotsByName(selectionFunction)

    def retranslateUi(self, selectionFunction):
        _translate = QtCore.QCoreApplication.translate
        selectionFunction.setWindowTitle(_translate("selectionFunction", "MainWindow"))
        self.logout_button.setText(_translate("selectionFunction", "LOG OUT: sam"))
        self.change_clan_button.setText(_translate("selectionFunction", "CHANGE CLAN"))
        self.members_button.setText(_translate("selectionFunction", "Member Information"))
        self.war_button.setText(_translate("selectionFunction", "Clan Wars / CWL"))
        self.event_button.setText(_translate("selectionFunction", "Event Calendar"))
        self.function_description.setHtml(_translate("selectionFunction", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
import source


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    selectionFunction = QtWidgets.QMainWindow()
    ui = Ui_selectionFunction()
    ui.setupUi(selectionFunction)
    selectionFunction.show()
    sys.exit(app.exec_())
